version: '2'
services:
  web:
    build:
      context: .
      dockerfile: ./docker/rails/Dockerfile
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - "3000:3000"
      - "3035:3035"
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
      - ~/.ssh:/root/.ssh
    depends_on:
      - db  
  db:
    image: "postgres:9.6.13"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  bundle:
    driver: local
  db:
    driver: local
  redis:
    driver: local    